[GLOBAL]
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]
pants_version = "2.12.0"

[python]
enable_resolves = true
interpreter_constraints = ["==3.8.*"]
tailor_ignore_solitary_init_files = false

[python.resolves]
python-default = "lockfiles/python-default.lock"

[python-infer]
inits = true

[source]
root_patterns = [
  "/project1",
  "/project2",
]
